-- Supabase Database Schema for Innate Ability Project
-- Run this SQL in your Supabase SQL Editor

-- Create results table
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  email TEXT,
  answers JSONB NOT NULL,
  computed_result JSONB NOT NULL,
  is_paid BOOLEAN DEFAULT FALSE NOT NULL,
  unlocked_at TIMESTAMP WITH TIME ZONE
);

-- Add email column if table already exists
ALTER TABLE results ADD COLUMN IF NOT EXISTS email TEXT;
-- Add is_paid column if table already exists
ALTER TABLE results ADD COLUMN IF NOT EXISTS is_paid BOOLEAN DEFAULT FALSE NOT NULL;
-- Add unlocked_at column if table already exists
ALTER TABLE results ADD COLUMN IF NOT EXISTS unlocked_at TIMESTAMP WITH TIME ZONE;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_results_is_paid ON results(is_paid);

-- Enable Row Level Security (optional, adjust policies as needed)
ALTER TABLE results ENABLE ROW LEVEL SECURITY;

-- Policy to allow service role to do everything (server-side)
-- Note: Adjust these policies based on your security requirements
CREATE POLICY "Service role can do everything" ON results
  FOR ALL
  USING (true)
  WITH CHECK (true);
